name: Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run FastAPI
      run: uvicorn main:app --reload --host 0.0.0.0 --port 8080 &

    - name: Start ngrok and expose FastAPI
      run: |
        ~/ngrok/ngrok http 8080 > ngrok.log &
        sleep 10
        NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')
        echo "NGROK URL: ${NGROK_URL}"

    - name: Sleep for 24 hours
      run: sleep 86400
